### ISSUE TITLE
PGN parse issue

### ISSUE THREAD

**Issue by questsin** [jhlywa/chess.js#152] opened 2017-05-15 21:10 UTC
Issue parsing PGN with FEN.. Adding [SetUp "1"] seems to fix the issue, but if you read back the header, header options are missing :)
[Variation "#43 Chess: 5334 Problems"]
[Date "1994.??.??"]
[Round "-"]
[White "Mate in one"]
[Black "White to move"]
[Result "*"]
[FEN "8/8/8/6R1/4k3/2KN1r2/8/8 w - - 0 1"]

1.Re5#

**Comment by siansell** [comment] 2017-06-20 21:58
This is a duplicate of #129, for which I have just submitted PR #154.

**Comment by jhlywa** [comment] 2020-02-25 03:01
Fixed in #154

**Closed by jhlywa** 2020-02-25 03:01 UTC
