### ISSUE TITLE
Does not accept over-disambiguated SAN moves

### ISSUE THREAD

**Issue by sesse** [jhlywa/chess.js#99] opened 2015-12-23 16:32 UTC
Hi,

I hit a problem today with SAN being somehow underspecified. Look at this case:

board = new Chess("1r5k/6p1/3p3p/8/8/4bQ2/2R3PP/2KRq3 w - - 6 44")
board.move("Rcd2")

The problem is that there are two rooks that can reach d2 (at c2 and d1). However, the rook at d1 cannot _strictly_ reach d2, since doing that would put the king in check.

Different programs deal with this differently; I've seen programs that disambiguate (Rcd2) and programs that don't (Rd2). In an attempt at being compatible with less intelligent programs, which cannot accept Rd2, my program outputs the safe choice, but seemingly chess.js doesn't accept this. (It _does_ accept Rd2.)

Would it be possible to make chess.js accept the over-disambiguated version?

**Comment by jhlywa** [comment] 2015-12-23 20:39
Yes, we're currently working this into the next release.

This is issue seems to be popping up quite a bit over the last month.  For the record, over-disambiguation is incorrect according to section 8.2.3.4 of the PGN spec.  The next release will have something like `chess.load_pgn({sloppy: true})` to handle situations like this.

This is a duplicate of issue #87 so I'm going to close it and suggest we keep discussion over there.

**Comment by sesse** [comment] 2015-12-23 20:45
FWIW, I don't do this from PGN, so you'll need a parameter to move() as well.

**Comment by jhlywa** [comment] 2016-06-08 02:49
0.10.0 should fix this issue now.  Use the sloppy parameter to force the parsing of any over disambiguation (e.g. `chess.move('Rcd2', {sloppy: true})`

**Comment by Kescay** [comment] 2016-06-09 12:21
The sloppy-mode in .move() works for overdisambiguations, but it not seem to accept the correctly disambiguated moves.

chess.load_pgn("1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 d5 5.exd5 Nxd5 6.Nxf7 Kxf7 7.Qf3+ Ke6 8.Nc3")
> true
chess.move("Nb4", {sloppy: true})
> null
chess.move("Ncb4", {sloppy: true})
> Object {color: "b", from: "c6", to: "b4", flags: "n", piece: "n"…}

**Comment by jhlywa** [comment] 2016-06-10 00:37
I'll change the logic to always try the strict parser first, then fall back to the sloppy parser if the move isn't found.

**Comment by jhlywa** [comment] 2016-06-10 02:02
Go ahead and give 0.10.1 a try.

**Comment by Kescay** [comment] 2016-06-10 15:35
Works!

**Closed** 2016-06-10 21:43 UTC
