### ISSUE TITLE
Unable to load correct PGN

### ISSUE THREAD

**Issue by yanongena** [jhlywa/chess.js#87] opened 2015-11-26 10:49 UTC
It seems that there might be a bug in the load_pgn method. 
When using following PGN: 

[Event "Live Chess"]
[Site "Chess.com"]
[Date "2015.11.10"]
[White "Passero82"]
[Black "bgknight"]
[Result "0-1"]
[WhiteElo "1175"]
[BlackElo "1255"]
[TimeControl "30|0"]
[Termination "bgknight won by resignation"]

1.e4 e5 2.Nf3 d6 3.d4 Bg4 4.dxe5 Bxf3 5.Qxf3 dxe5 6.Qf5 Nc6 7.Bb5 Nge7 8.Qxe5 Qd7 9.O-O Nxe5 10.Bxd7+ Nxd7
 11.Rd1 O-O-O 12.Nc3 Ng6 13.Be3 a6 14.Ba7 b6 15.Na4 Kb7 16.Bxb6 cxb6 17.b3 b5 18.Nb2 Nge5 19.f3 Rc8 20.Rac1 Ba3
 21.Rb1 Rxc2 22.f4 Ng4 23.Rxd7+ Kc6 24.Rxf7 Bxb2 25.Rxg7 Ne3 26.Rg3 Bd4 27.Kh1 Rxa2 28.Rc1+ Kb6 29.e5 Rf8 30.e6 Rxf4
 31.e7 Re4 32.Rg7 Bxg7 0-1

and use:
var chess = new Chess();
chess.load_pgn(pgn); 

it returns false however applications like Fritz are able to read the PGN properly so I started to investigate and added some additional debug info in the load_pgn method. 

In this specific PGN, it seems like the algoritm thinks that the move 7... Nge7 is not a valid move. 

In this code from the load_pgn method:
for (var half_move = 0; half_move < moves.length - 1; half_move++) {
                move = get_move_obj(moves[half_move]);

                /* move not possible! (don't clear the board to examine to show the
                 * latest valid position)
                 */
                if (move == null) {
                    console.log("Invalid move for " + half_move + " " + moves[half_move]);
                    return false;
                } else {
                    make_move(move);
                }
            }

move == null for the half move 13 which is 7... Nge7

I have another PGN with the exact move:

[Event "Live Chess"]
[Site "Chess.com"]
[Date "2015.11.10"]
[White "awhichi"]
[Black "Passero82"]
[Result "0-1"]
[WhiteElo "1103"]
[BlackElo "1165"]
[TimeControl "30|0"]
[Termination "Passero82 won by checkmate"]

1.e4 e5 2.d4 exd4 3.Qxd4 Nc6 4.Qe3 d6 5.Bc4 Be6 6.Bb5 Nge7 7.Bxc6+ Nxc6 8.Nc3 Be7 9.Bd2 O-O 10.O-O-O Ne5
 11.Nf3 Nc4 12.Qe2 c5 13.a3 Qb6 14.Bf4 Qxb2# 0-1

load_pgn also fails to load the PGN here for the same move: Nge7.

**Comment by yanongena** [comment] 2015-11-26 10:51
I did some more research and the reason why it doesn't parse is because Ne7 is correct because you cannot move the other knight because of the check... 
Although the notation seems fine, it's strange that this use case returns a false.

**Comment by jhlywa** [comment] 2015-11-26 12:24
Technically, the PGN that Chess.com is generating is invalid.  Here's a blurb from the Section 8.2.3.4 of the [PGN spec](http://www6.chessclub.com/help/PGN-spec):

> Note that the above disambiguation is needed only to distinguish among moves of
> the same piece type to the same square; it is not used to distinguish among
> attacks of the same piece type to the same square.  An example of this would be
> a position with two white knights, one on square c3 and one on square g1 and a
> vacant square e2 with White to move.  Both knights attack square e2, and if
> both could legally move there, then a file disambiguation is needed; the
> (nonchecking) knight moves would be "Nce2" and "Nge2".  However, if the white
> king were at square e1 and a black bishop were at square b4 with a vacant
> square d2 (thus an absolute pin of the white knight at square c3), then only
> one white knight (the one at square g1) could move to square e2: "Ne2".

Should it still parse ... maybe.  I'm considering add a lazy mode to the PGN parser that'll handle ill-formed SAN and PGN.

**Comment by yanongena** [comment] 2015-11-26 12:55
It's not just chess.com but Fritz as well... 
Here's a PNG generated from Fritz where I just made the moves to highlight this use case: 

[Event "?"]
[Site "?"]
[Date "2015.11.26"]
[Round "?"]
[White "New game"]
[Black "?"]
[Result "*"]
[ECO "C31"]
[PlyCount "8"]

1. e4 e5 2. f4 d5 3. fxe5 Nc6 4. Bb5 Nge7 *

I do agree that it's not according to the PGN standards but if both chess.com and Fritz are making this mistake, maybe it's a good idea to include this in the parser. 

In my code I simply work around the issue by doing a pgn.replace("Nge7","Ne7") in case the PGN fails to load. 

On another note, chess24 also exports their PGN in an incorrect format. 
For example promoting a pawn to a queen is b1Q instead of b1=Q. This also result in a fail on the chess.js parser.

**Comment by jhlywa** [comment] 2015-11-26 14:00
I appreciate the feedback as I don't use Fritz or chess24.  I'm _really_ surprised that all of these sites and apps spit out invalid SAN. Promotion is defined in Section 8.2.3.3 of the [PGN spec](http://www6.chessclub.com/help/PGN-spec):

> Pawn promotions are denoted by the equal sign "=" immediately following the destination square with a promoted piece letter (indicating one of knight, bishop, rook, or queen) immediately following the equal sign.  As above, the piece letter is in upper case.

So if we had to start making a list of parsing rules to relax, we'd have:

- allow disambiguation even if it's not needed (e.g. Nge7 vs Ne7)
- allow abbreviated promotion notation (e.g. e8Q vs e8=Q)

What other formatting should be relaxed?

**Comment by yanongena** [comment] 2015-11-26 14:10
Meanwhile I've handled a couple 100 games and these are the only problems so far. 
I've added the following in my code to handle for this problem: 
game = game.replace("Nge7","Ne7").replace("1Q","1=Q").replace("8Q","8=Q");
It's not fault proof but it solves all the problems so far... 

I'll be imported lots more games in the next few days so I will update this thread if I encounter more of these discrepancies.

**Comment by Kescay** [comment] 2016-06-07 12:40
Popped in to say thanks for the chess.js! I'm using it at my opening explorer at [www.chesstree.net](http://www.chesstree.net). The overdisambiguation is a problem in my site as well, since i'm using a database generated with fritz, and also people can import pgn's with overdisambiguation.

**Comment by jhlywa** [comment] 2016-06-08 01:39
I just coded up a fix for this.  You'll need to add optional sloppy boolean to your `load_pgn()` call.  See below:

```js
var Chess = require('./chess.js').Chess;
var chess = new Chess();

var pgn = ['[Event "?"]',                                                          
           '[Site "?"]',                                                           
           '[Date "2015.11.26"]',                                                  
           '[Round "?"]',                                                          
           '[White "New game"]',                                                   
           '[Black "?"]',                                                          
           '[Result "*"]',                                                         
           '[ECO "C31"]',                                                          
           '[PlyCount "8"]\n',                                                     
           '1. e4 e5 2. f4 d5 3. fxe5 Nc6 4. Bb5 Nge7'].join('\n');

// this will return false and fail on move 4... Nge7
console.log(chess.load_pgn(pgn));

// this will return true
console.log(chess.load_pgn(pgn, {sloppy: true})
```

Let me add a few tests and I'll push it up.

**Comment by jhlywa** [comment] 2016-06-08 02:46
I believe 0.10.0 should fix your issue.

**Comment by Kescay** [comment] 2016-06-08 12:04
Nice. Works for me. Thanks!

**Closed** 2016-06-08 14:03 UTC

**Comment by txumai** [comment] 2016-08-06 11:31
the problem is that duple TimeControl separate whith /  and many separate with : finally dead subita after : , so  "40/7200:3600"

**Comment by alcalawil** [comment] 2023-07-17 01:24
I got a similar problem. It seems that some chess programs use a different pgn format, so I replaced 0-0 with O-O (not the number zero)

**Comment by Pratikdubey7735** [comment] 2025-01-12 08:15
> I believe 0.10.0 should fix your issue.

Sir I am also facing similar issue while parsing a pgn for few pgns it's working but for few pgns it's saying Invalid pgn. COuld you please help me I am working on my college project and I am stuck on this point .I am Including pgn and my code for it 

[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "Gioachino Greco"]
[Black "NN"]
[Result "*"]
[Annotator "Copyright©Upstep Academy"]
[PlyCount "33"]
[EventDate "1620.??.??"]

{This game was played in the year 1620. We will learn king hunt. Sacrificing material and giving a series of checks to bring the opponent king in your territory and then checkmating him. ...} 1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. Ng5 d5 5. exd5 Nxd5 6. Nxf7 Kxf7 7. Qf3+ Ke6 8. Nc3 Nce7 9. O-O c6 10. Re1 Bd7 11. d4 Kd6 12. Rxe5 Ng6 13. Nxd5 Nxe5 14. dxe5+ Kc5 15. Qa3+ Kxc4 16. Qd3+ Kc5 17. b4# 1-0

It's telling invaid when it's parsing move 8th Nce7 . while for few pgns it going correct
